### ISSUE TITLE
Don't focus when you got disconnected

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1247]
My last patch was working here, but anyway, since it was removed, if anyone has an alternative to fix, would be cool.

Really annoying when it happen...

I was posting a issue before, I was typing the text and emesene window came up in my front, It's really annoying...

**Comment by lfottaviano** [comment]
I can't reproduce it. Are you using gnome? gtk3?

**Comment by jamesaxl** [comment]
Could you explain this bug clearly , and we need to know wich GUI are you using gnome or kde. 
N.B "you couldn't reproduce it also"

**Comment by Stiveknx** [comment]
gnome 2, libgtk2.0-0  2.24.10-0ubuntu6 ...

**Comment by Stiveknx** [comment]
Hm, when you reconnect, the event _on_account_key_release is called, and focus the password field ...
Since the field get focus the window also does too..

https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/Login.py#L403

My patch was working...
https://github.com/emesene/emesene/commit/fb46ae5db5a6686161b50d398b642d79d063270f

But it was throwing and error ...
To fix, I created another one, not accepted...
Than Sbte Reverted my changes because of this problem:
https://github.com/emesene/emesene/commit/14896180e3ad241ed1f362f84563cb2fc603ddac

Now, I don't want find another solution, so...

I created a video if anyone wants also ... ;d

**Comment by lfottaviano** [comment]
Share the video, i think it helps,  `_on_account_key_release` is called exactly when reconnection is in progress?

**Comment by Stiveknx** [comment]
After the 30s ...

Uploading the video ...

**Comment by Stiveknx** [comment]
In ogv format:
http://www.4shared.com/file/NSiRQHGf/out-2-4.html

In mp4 (temporary link:)
http://www3.online-convert.com/download-file/25c3b64c9054947386220ec745e978f7/converted-7f930662.mp4

**Comment by lfottaviano** [comment]
ok what I thought , I will commit something on my repo, if you can, connect to the IRC please

**Comment by lfottaviano** [comment]
@Stiveknx , please when you can, test, this issue should be fixed. Remember I can't reproduce exactly your situation.

**Comment by Stiveknx** [comment]
Yep, fixed :D

Thanks or should I say: Gracias ;d

Since this issue I've been having problems with it: #962

**Comment by lfottaviano** [comment]
isn't that issue fixed?

**Comment by Stiveknx** [comment]
No, didn't fixed, only now... I didn't report that wasn't fixed cause.... I don't know gg
