### ISSUE TITLE
[Single Window] Size of conversation window not save

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1282]
Reproduce:

1) Open Conversation
2) Set size you prefer
3) Close conversation
4) Open conversation

COnversation is always hide.

**Comment by Stiveknx** [comment]
About the always hide, must be related to this: #1281 (item 2)

And the size of the conversation, is not really not saved, should be a feature, even if you close, shutdown the computer and come back later, the size always the same ...

**Comment by Sbte** [comment]
@zipatei if you mean that sometimes it acts like this

http://imageshack.us/photo/my-images/193/c10ud.png/

then yes, that's what I've been looking into for two days now. I can't seem to get it to do what I want...

**Comment by c10ud** [comment]
this should be fixed in current head

**Comment by zipatei** [comment]
Miss one thing... emesene not record last size when you close emesene.

**Comment by zipatei** [comment]
i think this broke the first thing. i open conversation, and conversation is hide.

**Comment by Sbte** [comment]
Also after you set it to a bigger size once? I think you're still seeing the bug that we had before.

**Comment by zipatei** [comment]
Exactly. Even after putting a larger size, back to the beginning.

**Comment by Sbte** [comment]
And with 28d78befb5d8100abeb368e8e0af0088dafa0d70?

**Comment by zipatei** [comment]
Same... not fixed yet.

**Comment by zipatei** [comment]
@Sbte fe2a6956f664ea4a96188713331386c94f2e6c34 this commit broke this..

**Comment by Sbte** [comment]
@zipatei, can you come on irc?

**Comment by Sbte** [comment]
Maybe you could put that line before the while loop? I can't seem to reproduce your bug.

**Comment by zipatei** [comment]
srry @Sbte but I arrived just now.

I tried but not fixed.

But i remove this line and its fine...

**Comment by c10ud** [comment]
please test current git head

**Comment by c10ud** [comment]
nvm, fix ain't working

**Comment by c10ud** [comment]
bug is: the gtk resize isn't processed correctly and breaks the window

**Comment by c10ud** [comment]
please try now

**Comment by zipatei** [comment]
Not fixed... 

Now, this save windows size, but, always open conversation, back to hide conversation. (srry my english)

**Comment by zipatei** [comment]
Open coversation with size saved, but suddenlu back tho hide conversation.

**Comment by c10ud** [comment]
are you sure? i now almost see distinctly the conversation trying to appear in the wrong position and then expanding to the correct dimensions.. i'm trying with open/close in dummy

**Comment by zipatei** [comment]
here. the conversation trying to appear in the right position but after hide.

**Comment by KinG-InFeT** [comment]
agree the above ...

**Comment by c10ud** [comment]
trying to reproduce the issue but i can't anymore.

here's what i'm doing:
- 1 single window, dummy session
- 2 open one conversation or more
- 3 close conversation(s)
- goto 2

please check you're with today's git master c33ec537850c8f605fdafa8043b72fab0c88c819

**Comment by KinG-InFeT** [comment]
not fix....tries to re-open the window with the same opening as it was closed ... but fails and always returns to form "closed" on the right, and focus on the text area is still not working.

**Comment by zipatei** [comment]
This issue just occur when emesene is maximized...

**Comment by c10ud** [comment]
now that is a very useful comment
