### ISSUE TITLE
@hotmail.it email domain

### ISSUE THREAD

**Issue by iazel** [emesene/emesene#1396]
I can't see the avatar nor custom emoticons of my contacts with that domain, and also cannot receive file. The problem is reciprocal.

There's the emesene debug's log:
http://www.mediafire.com/?9238mgc8n5uk3e1

I don't know what part is important and what not, so I've uploaded all.
Thanks for all your work!

NOTE: For a privacy matter, I've substituted my email with "me@", my contacts ones with "___@" , and their nickname with "nickname".

**Comment by c10ud** [comment]
i looked at the trace and there's no obvious error:
- sometimes it's trying to make a direct connect but it fails because of your network configuration
- but this is fine since it's gracefully falling back to a transfer through servers (switchboard)

i have however identified some parts where some of those messages are rejected by the other party (msnp2p.transport.switchboard._on_error) with a "5" error code and i don't know what that means, i'm trying to find some references in the code but nothing so far

**Comment by c10ud** [comment]
also, this could be related to #1370 (even if its title is misleading)

**Comment by iazel** [comment]
Uhm, adding some more info hoping will help you.
Sometimes "Unable to deliver message" (or something like that) appears in chat windows, but actually it arrives. I've read of a same issues and the sources seems equal:
papyon.transport:<<< NAK 10
(18:57:03) papylib.Events:Error sending message: 4 1

I'm refereeing to this: #1172

Other times, in the debug window, a "Session.id == 0" will popup. I thought it refers to my @hotmail.it contact, but it's quite a while that doesn't appear.

The last strange behavior is about file transfer: one time only, the download request arrived and the preview was fine, but nothing happened when I've clicked on the accept button; instead cancel button worked.

Umm... Oh, the .it contact with which I usually chat, use WLM2009 on Windows7 64-bit and I'm using Ubuntu 12.04 64-bit (but I've experienced the same issues with prior versions of ubuntu also).
I've tried Win7 to Win7, emesene to emesene and nothing seems changed.

Again, sincerely thanks and if I can help you with some specific test, ask! :)

**Comment by iazel** [comment]
Uhm, I've tried others MSN clients and the only one that seems not having problems with this kind of domain is aMSN (in the previous version of ubuntu at least).
Thinking at the file transfer's acceptance problem, I've looked at its source and the message sent seems equals: 200. Doesn't it strange?

I'm still a newbe in this field, sorry I can't help more...

**Comment by pepeleproso** [comment]
@c10ud  about the error 5
In papyon/errors.py

```
CONTENT_ROAMING = 5
"Content roaming related errors"
```

**Comment by iazel** [comment]
Ok, another awkward behaviour: I've just noticed that in Linux with some @hotmai.it contacts can see avatar, file transfers work, but can't see emoticons. One of those utilize WLM2009 also... So, what the hell is the difference with my others friend!? O_o

**Comment by c10ud** [comment]
@pepeleproso it is weird that a content roaming error appears in there, i don't trust papyon in this case..

@Iazel emoticons are transferred only if you don't have them in cache (i guess other clients also do this) otherwise the cached version is showed.. so it can be that the transfer fails (and this could be a consequence of "file transfers fail after the 1st one" which could be then renamed to "p2p fails after 1st transfer")

**Comment by iazel** [comment]
I've got an idea: this problem can be related to NAT? If yes, what port it utilizes?

**Comment by c10ud** [comment]
fixed disabling direct connect

**Comment by iazel** [comment]
Sorry for my ignorance, but how can I disabling direct connection?

**Comment by c10ud** [comment]
just update to latest git

**Comment by iazel** [comment]
I've updated to the latest version, but problems still remain

**Comment by c10ud** [comment]
try again now

**Comment by iazel** [comment]
This one is better and works with more contacts than before, but still with others (included the usual one) the problems remain (always ".it"). I've also tried to use a port forwarded by the router, but nothing changed.

When launched in console, this warnings will be reported:
[23:15:28 WARNING papyon.service] Metadata: Invalid metadata
[23:15:46 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:15:48 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:15:53 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:15:54 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:16:03 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:16:08 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:16:18 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[23:16:19 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

It seems to be one for each online contact.

**Comment by Sbte** [comment]
The above warnings could be related to 757ee3409bda5accd718a21f0dc6d1250dca38ab

**Comment by c10ud** [comment]
warnings are just crappy clients unrelated to all of this, you can safely ignore them
