### ISSUE TITLE
latest emesene is broken (doesn't work) in Ubuntu 12.10

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1537]
Hello,

I just installed today Ubuntu 12.10, beta 2 and I used the PPA (https://launchpad.net/~emesene-team/+archive/emesene-stable) to install emesene.

I open the program, it opens correctly, but when the program crashes when it gets connected to the server. I don't know if this is emesene's fault or this is a problem with the server.

[09:15:57 DEBUG papyon.transport] >>> VER 0 MSNP18 MSNP16 MSNP15
Segmentation fault (core dumped)

I will be grateful for any help on this.

**Comment by Sbte** [comment]
Last time I tried emesene on Ubuntu 12.10 it worked, even with Gtk3 mode, at least after I fixed some bugs. But then they broke the Messaging Menu, which I then fixed, and now this. Right before they release. Dammit...

Could you try two things:

run emesene with `USE_GI=1 python2 emesene.py`
run emesene with `gdb python2` -> `emesene.py` -> `r`

The first to see if Gtk3 still works, the second to see what segfaults.

**Comment by jrstravino** [comment]
IDEM
emesene -s
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 882, in run
    self.logger = Logger(self.path, self.db_name)
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 364, in __init**
    self._load_events()
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 396, in _load_events
    self.execute(Logger.SELECT_EVENTS)
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 598, in execute
    self.cursor.execute(query, args)
OperationalError: no such table: d_event

Falha de segmentação (imagem do núcleo gravada)

https://bugs.launchpad.net/ubuntu/+source/emesene/+bug/1055130

**Comment by Sbte** [comment]
@jrstravino problem for you seems to be a broken database. Try to remove the database file from ~/.config

**Comment by jrstravino** [comment]
@Sbte I removed the database from .config/emesene2 /
It does not solve the problem, we can see more people with the same problem here:
https://bugs.launchpad.net/ubuntu/+source/emesene/+bug/1055130

**Comment by Sbte** [comment]
I reproduced the initial problem in my Quantal installation, so I'll see if I can do a regression test to find out what we changed that makes it go BOOM.

**Comment by Sbte** [comment]
Ok, apparently all versions of emesene stopped working in Quantal...

Backtrace: http://pastebin.com/9c0Hhtuq

Seems to be a gstreamer error

Backtrace without gstreamer: http://pastebin.com/kDJBWqUW

So not a gstreamer error. Present in both backtraces are GPollable*Streams, so probably that...

**Comment by Sbte** [comment]
This is being tracked here:

https://bugs.launchpad.net/bugs/1050358

**Comment by Sacolevas** [comment]
Just as a comment, I installed again quantal (12.10) using the official release (not the beta) and I have seen that msn accounts work fine if I start using the qt4 interface (which looks a bit ugly at this moment, hehe, but it is the first time I use it). At least, I can see the people in my account. So I guess this is a GTK-related problem (once I start emesene and try to enter my msn account, it closes inmediately). 

I hope this can be solved, because it is a huge problem not to be able to use this wonderful program in a distro. 

Thanks for your attention

**Comment by pepeleproso** [comment]
@Sbte
New webkit is linked against gstreamer 1.0 so we load two different versions and then crash. try to comment gstreamer code in emesene/e3/common/Sounds.py and see if that helps.

I don't have gstreamer 1.0 yet, so I couldn't test this.

**Comment by Sbte** [comment]
@pepeleproso I already did in the second backtrace.

**Comment by pepeleproso** [comment]
oh, sorry I only see the first one. The only place I remember we use pyg_iowatch_data_free is in gnet on papyon. there we use the static bindings that are in both pygobject 2.28 and 3.x

**Comment by Sbte** [comment]
I'm following the unity mailing list, and there they talked about having only one source for a whole application. If that made its way to pygobject, then it's possible that the remove the source, after which we try to delete it again, and then boom. Anyhow, It's a bug in pygobject (which shouldn't segfault).

**Comment by pepeleproso** [comment]
Today I updated to pygobject 3.4 so I push a fix for Gst 1.0. Under archlinux emesene works fine with both gtk2 and gtk3.

**Comment by ammarabdulsalam** [comment]
is there is any version of emesene works with ubuntu 12.10 x64?

**Comment by Sacolevas** [comment]
Last time I checked emesene 1.6.3 worked and every emesene2 version I have tried crashes

**Comment by Sbte** [comment]
At the moment, I'm trying to trace this bug down by creating a small bit of segfaulting example code, but I did not manage to get it to segfault yet. If there is anyone else willing to try this out, then please do so.

**Comment by maccabbeo** [comment]
SEGMENTATION FAULT!!!

 emesene
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
/usr/share/emesene/emesene/gui/gtkui/**init**.py:102: GtkWarning: IA__gdk_error_trap_pop: assertion `gdk_error_traps != NULL' failed
  gtk.main()
Errore di segmentazione (core dump creato)

**Comment by ammarabdulsalam** [comment]
it works again in ubuntu 13.04 :-)

**Comment by Sbte** [comment]
Can someone test it in 12.10? It might be fixed there too now I found the cause of the problem.

Also, we might want to SRU this into 13.04, but for that, we need to make a release.

**Comment by yocox** [comment]
I am using 12.10, and still seg-fault ^^

So, is the problem caused by PyGObject? Is it possible to fixed the problem by update my pyobject?

Thank you in advance ^^
