### ISSUE TITLE
Phantom Group Chat

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#74]
Hi!
http://rapidshare.com/files/412636885/GroupChatError.tar.gz

Today, when I receive a message from some contact a Group Chat appear with the message, and some people is added randomly, if I write in the original tab chat the message is not received be the other people, if I write in the Group Chat tab the message is correctly delivered. And apparently the others participants do not receive anything.

In the .tar.gz, the Emesene output (but I don't know if is useful), and a self explanatory screenshot.

On Ubuntu 10.04 with Papyon 0.4.8

Regards!!!
Emesene2 rulezzzz  :D

**Comment by c10ud** [comment]
i think i need to enforce the use of papyon 0.5 since yesterday i bumped the requirements and put msnp18 by default...

**Comment by EibrielInv** [comment]
I've installed Papyon 0.4.9 from https://launchpad.net/ubuntu/+source/papyon and works fine :)

**Comment by marianoguerra** [comment]
so this is fixed? it seems by the last message from Eibriel

reopen if not

**Comment by SWOriginal** [comment]
this is not fixed so needs to be reopened, even using 0.4.9 it still happens .

i have also noticed contact display images no longer download not sure if this is even connected to papyon so if not i dont know where the issue lies :)

**Comment by c10ud** [comment]
read my response

**Comment by c10ud** [comment]
just use the gitsubmodule in emesene/e3/papylib/papyon

**Comment by SWOriginal** [comment]
i thought this was fixed but its happening again, there's no obvious output in terminal so not sure whats happening

**Comment by EibrielInv** [comment]
with "git submodule update --init  emesene/e3/papylib/" I've installed papyon inside Emesene. Now how I tell emesene to use this library instead of the installed with Synaptic? Thanks!

**Comment by c10ud** [comment]
it imports that folder before the system one, so no need for that :)

**Comment by EibrielInv** [comment]
The error remains, the bug must be reopen. :S
I've deleted the emesene2 config folder, without result.

Regards!

**Comment by EibrielInv** [comment]
Hi!!!
Now I get this error on login:

```
[papyon] oim state changed 0
[papyon] oim state changed 1
[papyon] oim state changed 2
Traceback (most recent call last):
File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 138, in request_callback
type = http_response.get_header('Content-Type')#.split('/')[1]
File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/gnet/message/HTTP.py", line 51, in get_header
return self.headers[name]
File "/usr/lib/python2.6/UserDict.py", line 22, in __getitem__
raise KeyError(key)
KeyError: 'Content-Type'
```

Sounds like a mix between the .deb Papyon and the Submodule isn't?

**Comment by c10ud** [comment]
this one is a bug related to a 404 answer when requesting your profile picture, i also have this, i was trying to fix it with papyon developers just yesterday...it doesn't happen to every1

**Comment by EibrielInv** [comment]
Now is properly fixed :)

**Comment by c10ud** [comment]
yes, papyon 0.5.1
