### ISSUE TITLE
Nick render extension: CallRenderPlus color error

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#751]
I've noticed that whenever a contact uses a color code in his personal message, his email address in the chat window is rendered with the same color, instead of the default one. Of course, this doesn't happen with CallRenderNoPlus.
Here's a pic:
http://i20.photobucket.com/albums/b205/AnimusSN/x-1.jpg

**Comment by Sbte** [comment]
@pepeleproso did a lot of plus work recently. Maybe this is fixed now?

**Comment by Soulsuke** [comment]
Just checked with the latest git, the issue is still there

**Comment by Sbte** [comment]
What tags are those? Old or new style tags? ([c=red] or $3 or something)

**Comment by Soulsuke** [comment]
Oh right, I actually forgot there are two ways to do that... Using ·$4 to set the color the problem still happens, while with the  [c=red]...[red] format it doesn't. I guess it's because the first format doesn't actually require the terminate sequence to apply the color (I recall it being ·0, but it doesn't actually put back the original color, at least on emesene... And I can't test it on WLM at the moment).
By the way, I've noticed that now, while in the chat window the personal message is right, on the contacts window "no-more-color" is added to it (eg. "test" becomes "testno-more-color"), but just when using the ·$4 format

**Comment by pepeleproso** [comment]
if you had the following personal message "·$3 ..."
Plus parser detect unclosed color tag and put a </span> at end, but we pass personal message and mail in the same string resulting in something like this 
"< span foreground="#009300" > ...\n< span size="smal" >cloud@emesene.org< /span >< /span >"

the last  < /span > should be before the '\n'

**Comment by Sbte** [comment]
I'll fix this. It's most likely an issue in the contactlistparser.
